spring.profiles.active=dev

spring.application.name=platzi-play
server.servlet.context-path=/platzi-play/api

langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

# Specify the driver class name (optional for modern Spring Boot, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configure JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true